# Generated by Django 6.1.1 on 2026-10-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='All categories this product belongs to', related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='store.category'),
        ),
    ]
