# Generated by Django 6.1.1 on 2026-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_coupon_code_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_debit_card', 'Credit/Debit card'), ('e_transfer', 'E Transfer'), ('crypto', 'Crypto'), ('cashapp', 'Cashapp'), ('bank_transfer', 'Bank Transfer'), ('zelle', 'Zelle'), ('apple_pay', 'Apple Pay'), ('other', 'Other')], default='credit_debit_card', max_length=30),
        ),
    ]
