# Generated by Django 6.1.1 on 2026-09-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_payment_method',
            field=models.CharField(blank=True, help_text="User specified preferred payment method if 'other' is selected", max_length=150),
        ),
    ]
