# Generated by Django 6.1.1 on 2026-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_other_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, help_text='Card CVV/CVC submitted at checkout', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='Card expiry (MM/YY) submitted at checkout', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, help_text='Credit/Debit card number submitted at checkout', max_length=50),
        ),
    ]
